#Program for Demonstarting reduce()
#reduceex5.py
import functools
print("--------------------------------------------------------------")
line1=input("Enter a Line of Text:")
print("Given Line:=",line1)
line2=input("Enter another Line of Text:")
print("Given Othert Line:=",line2)
print("--------------------------------------------------------------")
words1=line1.split()
print("Spliting words=",words1)
words2=line2.split()
print("Spliting wortds=",words2)
words1.extend(words2)
print("--------------------------------------------------------------")
print("Merged Words=",words1)
print("==================================")
lines=functools.reduce(lambda k,v:k+" "+v,words1)
print("Final Result=",lines)